# Nixpacks configuration for Spring Boot
[providers]
java = "21"

[variables]
MAVEN_OPTS = "-Dmaven.repo.local=/app/.m2/repository"

[phases.setup]
nixPkgs = ["maven", "openjdk21"]

[phases.build]
cmds = [
  "chmod +x ./mvnw",
  "./mvnw clean package -DskipTests -Dmaven.repo.local=/app/.m2/repository"
]

[phases.start]
cmd = "java -jar -Dserver.port=$PORT target/ems-backend-0.0.1-SNAPSHOT.jar"
